name: Deploy Backend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to VPS
        run: |
          cd /opt/apps/RudyBackend
          git pull
          mvn clean package -DskipTests
          sudo systemctl restart rudy
